In [1]:
pip install copernicusmarine

Looking in indexes: http://mirrors.aliyun.com/pypi/simple
Note: you may need to restart the kernel to use updated packages.


In [1]:
import cupy as cp
x = cp.arange(6).reshape(2, 3).astype('f')
print(x)

[[0. 1. 2.]
 [3. 4. 5.]]


In [3]:
import os
os.environ['JAX_PLATFORM_NAME'] = 'interpreter'

import jax
from jax import numpy as jnp

x = jnp.array([1.0, 2.0, 3.0])
print(jnp.sin(x))

[0.841471   0.90929747 0.14112   ]


In [5]:
import jax
print(jax.devices())

[cuda(id=0)]


In [4]:
import jax
print("JAX版本:", jax.__version__)

print(jax.devices()[0])
import jax  
import jax.numpy as jnp  
  
print("Number of GPUs available:", jax.local_device_count())  
  
x = jnp.ones((2, 2))  
y = jax.lax.scan(lambda carry, x: (carry + x, x), jnp.zeros(2), x)  

y_val = jax.device_put(y, jax.devices('gpu')[0])  
print(y_val)

JAX版本: 0.4.27
cuda:0
Number of GPUs available: 1
(Array([2., 2.], dtype=float32), Array([[1., 1.],
       [1., 1.]], dtype=float32))


In [ ]:
import copernicusmarine

copernicusmarine.subset(
  dataset_id="cmems_mod_glo_phy_my_0.083deg_P1D-m",
  variables=["siconc", "sithick", "so", "thetao", "zos", "usi", "vsi"],
  minimum_longitude=-180,
  maximum_longitude=179.9166717529297,
  minimum_latitude=-90,
  maximum_latitude=90,
  start_datetime="2021-02-25T00:00:00",
  end_datetime="2021-06-30T00:00:00",
  minimum_depth=0.49402499198913574,
  maximum_depth=8.49402499198914,
)

username:

  jli54


password:

  ········


INFO - 2024-08-23T08:51:41Z - Dataset version was not specified, the latest one was selected: "202311"
INFO - 2024-08-23T08:51:41Z - Dataset part was not specified, the first one was selected: "default"
INFO - 2024-08-23T08:51:45Z - Service was not specified, the default one was selected: "arco-geo-series"
WARNING - 2024-08-23T08:51:49Z - Some or all of your subset selection [-90, 90] for the latitude dimension  exceed the dataset coordinates [-80.0, 90.0]
INFO - 2024-08-23T08:51:49Z - Downloading using service arco-geo-series...
INFO - 2024-08-23T08:51:54Z - <xarray.Dataset>
Dimensions:    (depth: 7, latitude: 2041, longitude: 4320, time: 126)
Coordinates:
  * depth      (depth) float32 0.494 1.541 2.646 3.819 5.078 6.441 7.93
  * latitude   (latitude) float32 -80.0 -79.92 -79.83 ... 89.83 89.92 90.0
  * longitude  (longitude) float32 -180.0 -179.9 -179.8 ... 179.8 179.8 179.9
  * time       (time) datetime64[ns] 2021-02-25 2021-02-26 ... 2021-06-30
Data variables:
    siconc     (tim

  y


INFO - 2024-08-23T08:51:57Z - Writing to local storage. Please wait...


  0%|          | 0/114914 [00:00<?, ?it/s]

In [1]:
import copernicusmarine

copernicusmarine.subset(
  dataset_id="cmems_mod_glo_phy_my_0.083deg_P1D-m",
  variables=["siconc", "sithick", "so", "thetao", "zos", "usi", "vsi"],
  minimum_longitude=-180,
  maximum_longitude=179.9166717529297,
  minimum_latitude=-90,
  maximum_latitude=90,
  start_datetime="2020-12-06T00:00:00",
  end_datetime="2021-06-30T00:00:00",
  minimum_depth=0.49402499198913574,
  maximum_depth=3.49402499198914,
)

username:

  jli54


password:

  ········


INFO - 2024-10-05T08:07:16Z - Dataset version was not specified, the latest one was selected: "202311"
INFO - 2024-10-05T08:07:16Z - Dataset part was not specified, the first one was selected: "default"
INFO - 2024-10-05T08:07:20Z - Service was not specified, the default one was selected: "arco-geo-series"
WARNING - 2024-10-05T08:07:24Z - Some or all of your subset selection [-90, 90] for the latitude dimension  exceed the dataset coordinates [-80.0, 90.0]
INFO - 2024-10-05T08:07:24Z - Downloading using service arco-geo-series...
INFO - 2024-10-05T08:07:29Z - <xarray.Dataset>
Dimensions:    (depth: 3, latitude: 2041, longitude: 4320, time: 207)
Coordinates:
  * depth      (depth) float32 0.494 1.541 2.646
  * latitude   (latitude) float32 -80.0 -79.92 -79.83 ... 89.83 89.92 90.0
  * longitude  (longitude) float32 -180.0 -179.9 -179.8 ... 179.8 179.8 179.9
  * time       (time) datetime64[ns] 2020-12-06 2020-12-07 ... 2021-06-30
Data variables:
    siconc     (time, latitude, longitude)

  y


INFO - 2024-10-05T08:07:31Z - Writing to local storage. Please wait...


  0%|          | 0/109298 [00:00<?, ?it/s]

INFO - 2024-10-05T08:28:01Z - Successfully downloaded to cmems_mod_glo_phy_my_0.083deg_P1D-m_multi-vars_180.00W-179.92E_80.00S-90.00N_0.49-2.65m_2020-12-06-2021-06-30.nc


PosixPath('cmems_mod_glo_phy_my_0.083deg_P1D-m_multi-vars_180.00W-179.92E_80.00S-90.00N_0.49-2.65m_2020-12-06-2021-06-30.nc')

In [5]:
pip install netCDF4

Looking in indexes: http://mirrors.aliyun.com/pypi/simple
Note: you may need to restart the kernel to use updated packages.


In [7]:
import netCDF4 as nc

file_path = 'cmems_mod_glo_phy_my_0.083deg_P1D-m_multi-vars_180.00W-179.92E_80.00S-90.00N_0.49m_2019-07-28-2019-11-28_(1).nc'
dataset = nc.Dataset(file_path)

print(dataset.variables.keys())
print(dataset.dimensions)

for var_name in dataset.variables:
    print(f"变量名: {var_name}")
    print("属性:")
    for attr_name, attr_value in dataset.variables[var_name].__dict__.items():
        if not attr_name.startswith("_"):
            print(f"  {attr_name}: {attr_value}")
    print("维度:")
    print(f"  {dataset.variables[var_name].dimensions}")
    print("\n")

dataset.close()

dict_keys(['depth', 'latitude', 'longitude', 'time', 'so', 'thetao', 'zos', 'siconc'])
{'depth': <class 'netCDF4._netCDF4.Dimension'>: name = 'depth', size = 1, 'latitude': <class 'netCDF4._netCDF4.Dimension'>: name = 'latitude', size = 2041, 'longitude': <class 'netCDF4._netCDF4.Dimension'>: name = 'longitude', size = 4320, 'time': <class 'netCDF4._netCDF4.Dimension'>: name = 'time', size = 124}
变量名: depth
属性:
  axis: Z
  long_name: Depth
  positive: down
  standard_name: depth
  unit_long: Meters
  units: m
  valid_max: 0.49402499198913574
  valid_min: 0.49402499198913574
维度:
  ('depth',)


变量名: latitude
属性:
  axis: Y
  long_name: Latitude
  standard_name: latitude
  step: 0.08333587646484375
  unit_long: Degrees North
  units: degrees_north
  valid_max: 90.0
  valid_min: -80.0
维度:
  ('latitude',)


变量名: longitude
属性:
  axis: X
  long_name: Longitude
  standard_name: longitude
  step: 0.0833282470703125
  unit_long: Degrees East
  units: degrees_east
  valid_max: 179.9166717529297
  

In [ ]:
import torch
import netCDF4 as nc
from netCDF4 import Dataset
import numpy as np

# 指定数据路径
file_path = "/root/autodl-tmp/cmems_mod_glo_phy_my_0.083deg_P1D-m_multi-vars_180.00W-179.92E_80.00S-90.00N_0.49-2.65m_2021-01-06-2021-06-30.nc"

# 读取 NetCDF 文件
with nc.Dataset(file_path, 'r') as dataset:
    # 获取维度数据并转为 NumPy 数组
    lat = dataset.variables['latitude'][:]
    lon = dataset.variables['longitude'][:]
    time = dataset.variables['time'][:]
    level = dataset.variables['depth'][:]
    
    # 列出你要处理的变量
    variables_to_process = ['siconc', 'sithick', 'so', 'thetao', 'zos', 'usi', 'vsi']
    
    # 用来存储移动到 GPU 的张量
    gpu_data = {}
    
    # 遍历并处理每个变量
    for var in variables_to_process:
        if var in dataset.variables:
            # 读取变量数据并转为 NumPy 数组
            var_data = dataset.variables[var][:]  # (time, lat, lon)
            # 将 NumPy 数组转换为 PyTorch 张量，并移动到 GPU
            var_tensor = torch.tensor(var_data, dtype=torch.float32).cuda()
            # 存储到 gpu_data 字典中
            gpu_data[var] = var_tensor

# 示例：打印每个变量的张量形状
for var, tensor in gpu_data.items():
    print(f"{var} tensor shape: {tensor.shape}")

# 3. 执行降采样操作
def coarsen_data(data, factor):
    """在 GPU 上执行降采样操作"""
    # 使用 unfold 和 mean 在 lat 和 lon 维度进行降采样
    data_coarsened = data.unfold(2, factor, factor).unfold(3, factor, factor).mean(dim=(-1, -2))
    return data_coarsened

coarsen_factor = 4
for var in gpu_data:
    gpu_data[var] = coarsen_data(gpu_data[var], coarsen_factor)

# 4. 处理批次的时间维度
batch_size = 14
num_days = time.shape[0]
num_batches = num_days // batch_size
truncated_num_days = num_batches * batch_size

# 截断时间维度以适应完整批次
time_tensor = torch.tensor(time[:truncated_num_days], dtype=torch.float32).cuda()
for var in gpu_data:
    gpu_data[var] = gpu_data[var][:truncated_num_days]

# 重塑数据以创建批次
for var in gpu_data:
    gpu_data[var] = gpu_data[var].reshape((num_batches, batch_size, *gpu_data[var].shape[1:]))

# 5. 生成新的均匀间隔的经纬度坐标
lat_tensor = torch.tensor(lat, dtype=torch.float32).cuda()
lon_tensor = torch.tensor(lon, dtype=torch.float32).cuda()
new_lat = torch.linspace(lat_tensor.min(), lat_tensor.max(), lat_tensor.size(0)).cuda()
new_lon = torch.linspace(lon_tensor.min(), lon_tensor.max(), lon_tensor.size(0)).cuda()

# 对数据集进行插值（重采样）
def interp_data(data, new_lat, new_lon):
    """假设有插值函数, 这里用 nearest-neighbor 方式"""
    # 示例：这里只是返回原始数据，实际插值逻辑应根据需求实现
    return data

for var in gpu_data:
    gpu_data[var] = interp_data(gpu_data[var], new_lat, new_lon)

# 6. 将处理后的张量数据保存为 netCDF 文件
def save_to_netcdf(filename, data_dict, lat, lon, time):
    with Dataset(filename, 'w', format='NETCDF4') as ncfile:
        # 创建维度
        ncfile.createDimension('lat', lat.size(0))
        ncfile.createDimension('lon', lon.size(0))
        ncfile.createDimension('time', time.size(0))

        # 创建变量
        latitudes = ncfile.createVariable('latitude', 'f4', ('lat',))
        longitudes = ncfile.createVariable('longitude', 'f4', ('lon',))
        times = ncfile.createVariable('time', 'f4', ('time',))

        # 写入数据
        latitudes[:] = lat.cpu().numpy()
        longitudes[:] = lon.cpu().numpy()
        times[:] = time.cpu().numpy()

        # 创建数据变量
        for var, data in data_dict.items():
            data_var = ncfile.createVariable(var, 'f4', ('time', 'lat', 'lon'))
            data_var[:] = data.cpu().numpy()

output_path = "/root/autodl-tmp/processed_data.nc"
save_to_netcdf(output_path, gpu_data, new_lat, new_lon, time_tensor[:batch_size])

print(f"数据已成功保存到 {output_path}")


In [ ]:
import torch 
import netCDF4 as nc
from netCDF4 import Dataset
import numpy as np

# 指定数据路径
file_path = "/root/autodl-tmp/cmems_mod_glo_phy_my_0.083deg_P1D-m_multi-vars_180.00W-179.92E_80.00S-90.00N_0.49-2.65m_2021-01-06-2021-06-30.nc"

# 列出要处理的变量
variables_to_process = ['siconc', 'sithick', 'so', 'thetao', 'zos', 'usi', 'vsi']
gpu_data = {}

# 读取 NetCDF 文件
with nc.Dataset(file_path, 'r') as dataset:
    # 获取维度数据
    lat = dataset.variables['latitude'][:]
    lon = dataset.variables['longitude'][:]
    time = dataset.variables['time'][:]

    # 遍历并处理每个变量
    for var in variables_to_process:
        if var in dataset.variables:
            var_data = dataset.variables[var][:]
            var_tensor = torch.tensor(var_data, dtype=torch.float16)  # 使用半精度
            gpu_data[var] = var_tensor

# 示例：打印每个变量的张量形状
for var, tensor in gpu_data.items():
    print(f"{var} tensor shape: {tensor.shape}")

# 执行降采样操作
def coarsen_data(data, factor):
    """在 CPU 上执行降采样操作"""
    # 使用 unbind 和 mean 在 lat 和 lon 维度进行降采样
    data_coarsened = data.unfold(2, factor, factor).unfold(3, factor, factor).mean(dim=(-1, -2))
    return data_coarsened

coarsen_factor = 4
for var in gpu_data:
    gpu_data[var] = coarsen_data(gpu_data[var], coarsen_factor)

# 处理批次的时间维度
batch_size = 14
num_days = time.shape[0]
num_batches = num_days // batch_size
truncated_num_days = num_batches * batch_size

# 截断时间维度以适应完整批次
time_tensor = torch.tensor(time[:truncated_num_days], dtype=torch.float16)  # 使用半精度
for var in gpu_data:
    gpu_data[var] = gpu_data[var][:truncated_num_days]

# 重塑数据以创建批次
for var in gpu_data:
    gpu_data[var] = gpu_data[var].reshape((num_batches, batch_size, *gpu_data[var].shape[1:]))

# 生成新的均匀间隔的经纬度坐标
lat_tensor = torch.tensor(lat, dtype=torch.float16)  # 使用半精度
lon_tensor = torch.tensor(lon, dtype=torch.float16)  # 使用半精度
new_lat = torch.linspace(lat_tensor.min(), lat_tensor.max(), lat_tensor.size(0))
new_lon = torch.linspace(lon_tensor.min(), lon_tensor.max(), lon_tensor.size(0))

# 对数据集进行插值（重采样）
def interp_data(data, new_lat, new_lon):
    """假设有插值函数, 这里用 nearest-neighbor 方式"""
    # 示例：这里只是返回原始数据，实际插值逻辑应根据需求实现
    return data

for var in gpu_data:
    gpu_data[var] = interp_data(gpu_data[var], new_lat, new_lon)

# 将处理后的张量数据保存为 netCDF 文件
def save_to_netcdf(filename, data_dict, lat, lon, time):
    with Dataset(filename, 'w', format='NETCDF4') as ncfile:
        # 创建维度
        ncfile.createDimension('lat', lat.size(0))
        ncfile.createDimension('lon', lon.size(0))
        ncfile.createDimension('time', time.size(0))

        # 创建变量
        latitudes = ncfile.createVariable('latitude', 'f4', ('lat',))
        longitudes = ncfile.createVariable('longitude', 'f4', ('lon',))
        times = ncfile.createVariable('time', 'f4', ('time',))

        # 写入数据
        latitudes[:] = lat.numpy()
        longitudes[:] = lon.numpy()
        times[:] = time.numpy()

        # 创建数据变量
        for var, data in data_dict.items():
            data_var = ncfile.createVariable(var, 'f4', ('time', 'lat', 'lon'))
            data_var[:] = data.numpy()

output_path = "/root/autodl-tmp/processed_data.nc"
save_to_netcdf(output_path, gpu_data, new_lat, new_lon, time_tensor[:batch_size])

print(f"数据已成功保存到 {output_path}")
